version: "3.3"
services:
    mariadb:
      build: ./requirements/mariadb
      image: mariadb
      container_name: mariadb
      ports:
        - "3306:3306"
    #   volumes:
    #     - db:/var/lib/mysql
    #   restart: always
      env_file:
        - .env
    #   environment:
    #     MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
    #     MYSQL_DATABASE: ${DB_NAME}
    #     MYSQL_USER: ${DB_USER}
    #     MYSQL_PASSWORD: ${DB_PASSWORD}
      networks:
            - app-network

    wordpress:
      build: ./requirements/wordpress
      image: wordpress
      container_name: wordpress
      ports:
          - "9000:9000"
      depends_on:
        - mariadb
      env_file:
        .env
    #   environment:
    #     WORDPRESS_DB_HOST: ${DB_HOST}
    #     WORDPRESS_DB_USER: ${DB_USER}
    #     WORDPRESS_DB_PASSWORD: ${DB_PASSWORD}
    #     WORDPRESS_DB_NAME: ${DB_NAME}
      volumes:
          - wp:/var/www/html/wordpress
      networks:
        - app-network

    nginx:
      build: ./requirements/nginx
      image: nginx
      container_name: nginx
      depends_on:
        - wordpress
      ports:
        - "443:443"
      volumes:
        - wp:/var/www/html/wordpress
      networks:
        - app-network

volumes:
    db:
      name: db
      driver: local
      driver_opts:
        type: none
        o: bind
        device: /Users/eblastoi/data/mariadb
    wp:
      name: wp
      driver: local
      driver_opts:
        type: none
        o: bind
        device: /Users/eblastoi/data/wordpress

networks:
  app-network:
    driver: bridge