version: "3.6"
services:
    mariadb:
      build: ./requirements/mariadb
      image: mariadb
      container_name: mariadb
      ports:
        - "3306:3306"
      volumes:
        - db:/var/lib/mysql
    #   restart: always
      env_file:
        - .env
    #   environment:
    #     - DB_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
    #     - DB_NAME=${DB_NAME}
    #     - DB_USER=${DB_USER}
    #     - DB_PASSWORD=${DB_PASSWORD}
      networks:
            - eblastoi

    wordpress:
      build: ./requirements/wordpress
      image: wordpress
      container_name: wordpress
      ports:
          - "9000:9000"
      depends_on:
        - mariadb
      env_file:
        - .env
    #   environment:
    #     - DB_HOST=${DB_HOST}
    #     - DB_USER=${DB_USER}
    #     - DB_PASSWORD=${DB_PASSWORD}
    #     - DB_NAME=${DB_NAME}
      volumes:
          - wp:/var/www/html/wordpress
      networks:
        - eblastoi

    nginx:
      build: ./requirements/nginx
      image: nginx
      container_name: nginx
      depends_on:
        - wordpress
      ports:
        - "443:443"
      volumes:
        - wp:/var/www/html/wordpress
      networks:
        - eblastoi

volumes:
    db:
    #   name: db
      driver: local
      driver_opts:
        type: none
        o: bind
        device: /home/eblastoi/data/mariadb
    wp:
    #   name: wp
      driver: local
      driver_opts:
        type: none
        o: bind
        device: /home/eblastoi/data/wordpress

networks:
    eblastoi:
      driver: bridge