CREATE DATABASE IF NOT EXISTS wordpress;
CREATE USER '${DB_USER}'@'%' IDENTIFIED BY '${DB_PASSWORD}';
GRANT ALL ON wordpress.* TO '${DB_USER}'@'%' IDENTIFIED BY '${DB_PASSWORD}';
ALTER USER 'root'@'%' IDENTIFIED BY '${DB_ROOT_PASSWORD}';
FLUSH PRIVILEGES;
USE wordpress;
CREATE TABLE IF NOT EXISTS phone_book (name CHAR(20), phone CHAR(12));
